### ISSUE TITLE
format_number_to_units can give invalid result

### ISSUE THREAD

**Issue by DarkShadow44** [Deadlock989/IndustrialRevolution#139] opened 2022-12-29 22:29 UTC
**Describe the bug**
When `format_number_to_units` is called with "4950000" the result is "4.9.0M"
This will later crash factorio.

Problem is that line:
`local res = formatted..((amount < 100 and math.abs(amount) == amount) and ".0" or "")..(padding and " " or "")..suffix`
Did you maybe mean math.floor?

**Factorio version, IR version**
Factorio 1.1.74, IR3 3.0.4

**Other mods installed**
pymods change the fuel value, that's where this comes from.

**Comment by Deadlock989** [comment] 2022-12-29 22:49
Can you clarify if you are talking about the `DIR.format_number_to_units` function on line 198 of `functions-data-maths.lua` or some other version of this function somewhere else? Because that line doesn't appear exactly like that in IR3. But I can confirm your result.

I didn't actually write this function myself, I forget where I picked it up.

Py's mods are not supported by IR3 but if there is a general problem here I want to fix it.

**Comment by DarkShadow44** [comment] 2022-12-29 22:57
> Can you clarify if you are talking about the `DIR.format_number_to_units` function on line 198 of `functions-data-maths.lua`


Yes, that's what I mean. Sorry I forgot I modified the line to understand the problem.

> Py's mods are not supported by IR3 but if there is a general problem here I want to fix it.

Thanks. Yeah, I'm playing around with making them at least run together.

**Comment by Deadlock989** [comment] 2022-12-29 23:24
My post-Covid brain fog briefly parted to reveal a 3-4 years old memory of adapting this function from `util.format_number()` which is in the Factorio core `util` library, but the original very weirdly uses a B units prefix instead of G for giga. I was only originally using it for localised strings on tooltips (which is why the weird/broken attempt to get a .0 for whole numbers is there), it wasn't ever being used for converting energy values at that point, and then those tooltips all got stripped out sometime between IR1 and IR2. In the intervening time I forgot what it was originally for. IR3 only uses it once, for creating fuel barrels. Anyway, it's clearly broken.

I have revisited the original and stripped out the cruft from the current function. The "padding" boolean parameter which inserts a space has been removed (this was for printing only to match Factorio tooltip style and isn't needed by energy value properties). I took out the bit in the original function which forces rounding to one significant figure. It now gives a better result for 4950000 (4.95M). This will be included in the next released version.

```
function DIR.format_number_to_units(amount)
	local suffix = ""
	local suffix_list =	{
		["T"] = 1000000000000,
		["G"] = 1000000000,
		["M"] = 1000000,
		["k"] = 1000
	}
	for letter, limit in pairs (suffix_list) do
		if math.abs(amount) >= limit then
			amount = amount/limit
			suffix = letter
			break
		end
	end
	local formatted, k = amount
	while true do
		formatted, k = string.gsub(formatted, "^(-?%d+)(%d%d%d)", '%1,%2')
		if (k==0) then break end
	end
	return formatted..suffix
end
```

**Closed** 2022-12-31 14:36 UTC
Labels: fixed for next version
