### ISSUE TITLE
Electroplater stops working until manual intervention

### ISSUE THREAD

**Issue by doktorstick** [Deadlock989/IndustrialRevolution#339] opened 2023-11-22 03:51 UTC
There are times when the electroplater will get stuck and not accept inputs. I don't know if the problem is caused by low fluids or low power (both had happened prior to my examination), but both power and fluid levels recovered (100% power, ~15K fluid in reserve) and yet the machines remain stuck.

The stuck case is with an inserter holding the solid item (*e.g.*, steel plate for chrome plate) over the electroplater machine and the machine sitting idle. If you open the electroplater, you'll observe the fluid level fluctuates near full (the machines are in a series, and fluid flows to non-stuck machines) and the solid input empty. If you drop one input into the machine, it will unstick the machine and it will begin running normally with the inserter feeding the machine continuously. Alternatively, you can open the inserter and remove the held item and normal operation will begin anew.

In case it's relevant, in this specific case, the first electroplater in the series was continuing to operate. All others down-series were stuck in the described manner. 

**Factorio version**: 1.197 
**`IR` version**: 3.1.11

**Comment by Deadlock989** [comment] 2023-11-22 09:46
It sounds more like that the inserters are getting stuck rather than the electroplater. But did this ever happen in previous versions (3.1.9 and before)? There was a change to electroplater fluid box sizes in 3.1.10 (#329).

I'm not able to reproduce what you've found by cutting off input fluid supply or by removing power (i.e. suddenly dropping to zero power). Nor by supplying very low power - in the screenshot below, the outlined inserter had something in its hand when power was removed and then reinstated at about 2% level. In all three cases the inserter resumes (in slow motion in the last test).

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/47e73e09-0696-41a2-954a-5f86ea184810)

Are you able to supply a saved game or a blueprint string that illustrates the problem?

**Comment by Deadlock989** [comment] 2023-11-22 09:57
Your report also rang very faint bells from a recent bug report in the vanilla game: https://forums.factorio.com/viewtopic.php?f=230&t=105131

If it is the same phenomenon, then IR3 has always suffered from this and you are the first to notice, and it won't be fixed until Factorio 2.0 which could be nine months or a year away or more.

**Comment by Deadlock989** [comment] 2023-11-22 10:58
I just spent another hour testing and researching this issue and drew blanks. Still not able to reproduce it with electroplaters. Can't reproduce the barrelling machine behaviour in the forum bug report either (it sounds like Py barrelling machines are configured in the same way as IR3 barrelling machines). There is next to no documentation that I can find about the conditions under which entities go to sleep, just bits and pieces scattered hither and thither. The received wisdom seems to be that a furnace starved of item ingredients will go to sleep, but there is no event for fluid inputs, so a machine that is sleeping won't wake its inserters if it was previously starved of items and fluid and then receives new fluid. But I can't even reproduce that behaviour.

If this is really the issue and it's not some other more specific situation, it has implications for electroplaters, barrelling machines and ore washing plants - these are all furnace-type entities with both solid and fluid ingredients. The only guaranteed fix for it (bar waiting a year) would be turning them into assembling machines. That would be an annoyance for electroplaters and barrellers, but it would properly wreck the dynamic cold/hot water auto-switching mechanic for washing machines.

**Comment by doktorstick** [comment] 2023-11-22 14:33
I couldn't say if I saw this before you changed the fluid box size, and if I did it wasn't obvious like this one. In reading your through your investigation, and looking at the forum post, it tickles my brain. It feels like I've had to fix a one-off fluid machine before during my first playthrough in IR3, but it's quite hazy; I don't remember the machine but I do remember thinking it was odd.

This next bit is trippy. I found an auto-save before I fixed the problem, and saved it as a temporary save. I then disabled many mods--quality of life (like picker, factory planner), biter mods--mainly to reduce what you would have to sync. Load the temp or autosave and all inserters are feeding. I then loaded the save with "sync mods" and it doesn't happen anymore. Restarting and loading (from an all-mods-are-loaded state) still doesn't happen. It's almost as if the act of changing the mods/startup settings perform a re-init of the inserters and/or machines on map load, even if the end result of mods and settings are the same.

For the future, I'm not convinced if it reproduces again that I could give you a workable save given above (your system would need to sync mods/config). If it does happen again, though, I won't try to be *helpful*, and will just confirm I can load it multiple times and have it remain stuck before saving off the file for you.

>  That would be an annoyance for electroplaters and barrellers, but it would properly wreck the dynamic cold/hot water auto-switching mechanic for washing machines.

Yeah, I like that dynamic and removing it would be unfortunate.

I'm fine with this ticket being closed out as I suspect it is related to the bug that `Rseding91` found in vanilla. Regardless, I'll keep an eye out for it happening again.

**Comment by Deadlock989** [comment] 2023-11-22 15:42
> This next bit is trippy. I found an auto-save before I fixed the problem, and saved it as a temporary save. I then disabled many mods--quality of life (like picker, factory planner), biter mods--mainly to reduce what you would have to sync. Load the temp or autosave and all inserters are feeding. I then loaded the save with "sync mods" and it doesn't happen anymore. Restarting and loading (from an all-mods-are-loaded state) still doesn't happen. It's almost as if the act of changing the mods/startup settings perform a re-init of the inserters and/or machines on map load, even if the end result of mods and settings are the same.

This is very possible - it could well be that the active/sleep state of all machines is updated when you load a save, or maybe when a configuration change / migration is detected (changing mods or changing mod settings). But like everything else to do with active/sleep states, if this is documented anywhere, I haven't been able to find it.

I will close this for now but if you do find a reproduction method, let me know. I will also increase the electroplater fluid fluidbox size a little, somewhere in between the bare minimum it was taken down to in 3.1.10 and what it was before that, in case that is contributing (if running out of fluid is the trigger for the failure-to-wake bug, having a bigger buffer might help safeguard machines under low power against it, even if it doesn't fix the issue directly).

**Closed by Deadlock989** 2023-11-22 15:42 UTC
Labels: pending / more info needed

**Comment by simply-peachy** [comment] 2023-12-16 23:09
I've had this happen reliably as well, under the same circumstances. A design that suffers from the bug has the electroplaters fed with direct insertion from steel plate small assemblers.

Having more than one steel plate input source appears to solve the problem, with both the failure and successes proving on a magnitude of tens of thousands of finished products. My design had two pairs of electroplaters. One pair was fed by a single small assembler each, the pair of electroplaters were fed by two small assemblers. Those fed by two small assemblers never seem to choke. All of those with single inputs always choked.

Your test of feeding the electroplater via a belt might not trigger the problem as it could be you're feeding the platers fast enough to always avoid triggering it.
