### ISSUE TITLE
Add Electric Inserter variants to be upgradeable from Steam Inserters

### ISSUE THREAD

**Issue by Dimava** [Deadlock989/IndustrialRevolution#171] opened 2023-01-16 13:54 UTC
Steam and electric inserters can't be fast-replaced, because steam inserters should be fast-replaceable with utubes and electric ones shouldn't

For Upgrade Planner (which I think is the most important, as you always have bots) this issue can be solved by cloning `electric-inserter` as `electric-inserter-upgradeable` with fast-replace group set to `pipes`

The `electric-inserter-upgradeable` may be later replaced with `electric-inserter` with script on build event

**Comment by Deadlock989** [comment] 2023-01-16 14:37
Duplicate of #165, #136, #13. Can't be fixed because steam inserters need to fast-replace pipes and the game engine doesn't allow entities to be in more than one fast-replace group. Please check previous issues before making reports.

**Closed by Deadlock989** 2023-01-16 14:37 UTC
