### ISSUE TITLE
Script error due to non-validation in delayed flying text calls

### ISSUE THREAD

**Issue by RiptideSage** [Deadlock989/IndustrialRevolution#266] opened 2023-07-17 00:50 UTC
**Describe the bug**
After migrating to IR 3.1.1 I encountered a repeatable hard crash when the Flying Text for pollution tried to render. The error says the surface is invalid, so I locally added some debug and the floating text's position pointed to a Steam Crusher (or the attached steam pipe)  that was on the same steam fluid system as some Steam Mixers that were removed as part of the IR 3.1.1 version upgrade.

![FlyingTextCrash](https://github.com/Deadlock989/IndustrialRevolution/assets/4371777/9e647bbc-c867-4d7d-910f-2de39215abce)

Line numbers in the image are from before any local edits.

**Factorio version, IR version**
Factorio version number:  1.1.87-0
Industrial Revolution version number: 3.1.1

**Other mods installed**
No other mods installed.

**PS**
Thanks for making IR3! It's been a blast to play so far.

**Comment by Deadlock989** [comment] 2023-07-17 07:59
Ouch.

Could you let me have a copy of the save?

**Comment by tundy** [comment] 2023-07-17 10:40
Same thing, but I have lots of other mods.
[_autosave2.zip](https://github.com/Deadlock989/IndustrialRevolution/files/12068363/_autosave2.zip)
After I load save, wait for 5 seconds it crush.
I started playing with delivery plates to see how it works

**Comment by Deadlock989** [comment] 2023-07-17 10:54
Thank you. Fixed for next version which I will release soon.

This was unrelated to steam mixers being migrated - it was caused by insufficient validation on the new method of drawing delayed fading flying text, where it was possible that the Manifesto simulation could be deleted while a delayed draw text call was in the queue.

**Comment by Deadlock989** [comment] 2023-07-17 11:10
Fixed in 3.1.2, released.

**Closed by Deadlock989** 2023-07-17 11:10 UTC
Labels: fixed for next version
