### ISSUE TITLE
Steam assembler flipping

### ISSUE THREAD

**Issue by 7M351** [Deadlock989/IndustrialRevolution#249] opened 2023-06-26 12:15 UTC
**Describe the bug**
Blueprints with steam assemblers cannot be flipped. Even if the selected recipe takes a fluid, the corresponding flipped variant exists. This is the case even with small steam assemblers which cannot use fluids.
Laser assemblers cannot be flipped either but in this case, there are variants with two different coolants passing through, whose flipped versions do not exist.

**Factorio version, IR version**
Factorio 1.1.80, IR 3.0.19

**Other mods installed**
(none)

**Comment by Deadlock989** [comment] 2023-06-26 13:41
There is nothing I can do about this unfortunately.

Duplicate of #35, #39

https://forums.factorio.com/viewtopic.php?f=48&t=100988

**Closed** 2023-06-26 13:41 UTC
Labels: duplicate, vanilla issue / can't fix
