### ISSUE TITLE
IR cannot load with Factorio 1.1.101 due to bad recipe "forestry-wood-fertiliser-00"

### ISSUE THREAD

**Issue by doktorstick** [Deadlock989/IndustrialRevolution#361] opened 2023-12-27 02:09 UTC
*NOTE: I typed out the error; pardon typos*

The error based on the description might correspond to this changelog entry:
```
Modding:
    - Fluid ingredient amounts must be larger than zero.
```

**Error loading mods**
Failed to load mods: Error while loading recipe prototype "forestry-wood-fertiliser-00" (recipe): Difficulty normal: amount must be larger than 0 in property tree at ROOT.recipe.forestry-wood-fertiliser-00.ingredients[1]
Modifications: Industrial Revolution 3

**Factorio**: 1.1.101
**IR**: 3.1.14

**Other mods installed**
None, not even QoL

**Comment by alex-dev** [comment] 2023-12-27 05:28
Duplicate #358.

**Comment by Deadlock989** [comment] 2023-12-27 08:38
Duplicate of #358

**Closed by Deadlock989** 2023-12-27 08:38 UTC
