### ISSUE TITLE
Industrial Revolution + Cargo Ships = cant move anymore?

### ISSUE THREAD

**Issue by MagicManMe** [Deadlock989/IndustrialRevolution#366] opened 2023-12-28 05:47 UTC
**Describe the issue**
I opened factorio to play my IR3 save and I noticed I couldn't move. I was also unable to place any new buildings down except for belts, undergrounds, and splitters. It says cannot place on grass/stone brick/etc
**Factorio version, IR version**
Factorio version is 1.1.101 build62011
IR version was 3.1.14 then I updated to 3.1.15 thinking it'd fix it but no.
**Other mods installed**
I have several other mods installed, but tracked it down to cargo ships being the cause. When it is installed I cannot move or build in my save, taking it out and loading the save fixes it. Tried with every other mod aswell and they all worked fine. (Can post full list if needed)

**Comment by MagicManMe** [comment] 2023-12-28 05:49
I should've noted this only developed today, it was working fine before (last opened the game a few days ago). I did not update any mods when I noticed the issue. Only updated IR3 after noticing the issue had developed.

**Comment by Deadlock989** [comment] 2023-12-28 10:32
This is almost certainly the same issue as #365 - a fix will be available later today.

Duplicate of #365

**Closed** 2023-12-28 12:22 UTC
Labels: duplicate

**Comment by Deadlock989** [comment] 2023-12-28 12:23
This is fixed in 3.1.16 which was just released. If you encounter any more issues like this please start a new issue or add to an open issue. If you are using Cargo Ships I can recommend this add-on by TheIronRelic which improves compatibility with IR3:

https://mods.factorio.com/mod/IR3CargoShips

**Comment by MagicManMe** [comment] 2024-01-04 07:38
Hey sorry, have been without internet for a bit. Yep! you were completely right, updated and completely fixed thank you!! <3

**Comment by MagicManMe** [comment] 2024-01-04 07:39
Also got the addon you suggested!
