### ISSUE TITLE
Steam inserters not upgradable

### ISSUE THREAD

**Issue by abueth** [Deadlock989/IndustrialRevolution#165] opened 2023-01-10 18:27 UTC
Steam inserters and long hand steam inserters are not upgradable, meaning when editing an upgrade planner they are not selectable and if using an empty upgrade planner, they are unaffected.
I would expect them to be upgraded to an electric inserter equivalent.

Factorio version: 1.1
Industrial Revolution 3 version: 3.0.8

**Comment by Deadlock989** [comment] 2023-01-10 18:52
This isn't possible due to game engine limitations and the more often-used requirement of having them be fast-replaceable with pipes.

Duplicate of #13

**Closed by Deadlock989** 2023-01-10 18:52 UTC
Labels: duplicate
