### ISSUE TITLE
Transfer plates are less smart than SHIFT-E

### ISSUE THREAD

**Issue by Cadams111** [Deadlock989/IndustrialRevolution#386] opened 2024-01-28 23:01 UTC
**Describe the issue**
When triggering a delivery plate, it will not pull items from ANY chest that is filtered to go into another chest. For example, chest 1 has tin plates, inventory is “requesting” tin plates, chest 2 is “requesting” tin plates. When I press Shift-E on Chest 1 the tin plates zwoop from chest 1 to me. Then Shift-E on Chest 2 sends the tin plates to it. But transfer plates never take the tin plates that I want from Chest 1. Can the transfer plates be configured to take items from unfiltered chests and THEN see if there is a chest that wants them? I understand that it should not just steal all the tin plates from Chest 2 just to put them right back, but the goal is to automatically send them to 2 from 1 while I’m standing on the plate.

**Factorio version, IR version**
Most recent as of 2024/01/28

**Other mods installed**
Just the IR3 add on packs

**Comment by Deadlock989** [comment] 2024-01-29 11:32
Duplicate of #322. Transfer plates aren't intended to automate chest-to-chest logistics like this - inserters/loaders with filters already have that function. The floor plates are all about topping up your personal inventory and dumping trash as a holdover until you get personal bot logistics. The hotkey has a little more finesse because you can influence the order of operations (chest 1 then chest 2) but to a plate, it's just a bunch of chests in no meaningful order. I don't want to complicate it any further at this time.

**Closed by Deadlock989** 2024-01-29 11:32 UTC
Labels: duplicate
