### ISSUE TITLE
1x1 fluid handling machines broken by third party mod

### ISSUE THREAD

**Issue by Pthread-Create** [Deadlock989/IndustrialRevolution#256] opened 2023-07-07 19:04 UTC
**Describe the bug**
I think it's all machine 1x1 like the barelling, air compressor, ambient heat exhanger, and the small buffer tank
When you copy the machine with the pipe, the pipes are not connected when placed by robots.
Should be like this 
![factorio_zIVhKx61FF](https://github.com/Deadlock989/IndustrialRevolution/assets/17547226/3d51e79c-045a-4b8b-8999-c732ec55ca44)
but it end up like this
![factorio_iHDrUYQtPY](https://github.com/Deadlock989/IndustrialRevolution/assets/17547226/cb0dd2bc-3e2c-490b-b420-b6507f41bc67)

**Factorio version, IR version**
base 1.1.80
ir3 3.0.19

**Other mods installed**
248k

**Comment by Pthread-Create** [comment] 2023-07-07 19:10
also do you have a discord server for your factorio addons, I would love to share some creation and suggestions

**Comment by Deadlock989** [comment] 2023-07-07 19:54
Cannot reproduce this with IR3 alone. Please list the other mods you have installed, there is one in particular known to cause this kind of behaviour with 1x1 machines.

**Comment by Pthread-Create** [comment] 2023-07-07 20:05
I can provide you the save I'm playing on with friends on a dedicated server : 
https://cdn.discordapp.com/attachments/170196272572137473/1126966990544834580/IndusRev_7.zip

**Comment by Deadlock989** [comment] 2023-07-07 20:13
You have IR3 Squeak Through installed. See #199 

Also see https://mods.factorio.com/mod/IR3_Squeak_Through/discussion/63f7e68210e4a2431f648576

This mod will be marked as incompatible in the next release of IR3.

**Closed** 2023-07-14 13:40 UTC
Labels: duplicate, fixed for next version, other mod
