### ISSUE TITLE
Cant connect via Multiplayer

### ISSUE THREAD

**Issue by Leximo14** [Deadlock989/IndustrialRevolution#116] opened 2022-12-25 11:48 UTC
**Describe the bug**
When trying to join a Multiplayer Game via Steam there is a error message:
![image](https://user-images.githubusercontent.com/62356085/209466624-de085513-9243-4856-b157-e8f247eb2b7f.png)
Wich translates to:
Note
Can not join. The following control programs for mod events
do not match those of the server. This suggests that
these mods cause problems in the multiplaver (when saving/loading)
can. (More details in the log file):
mod-Industrial revolution3

**Factorio version, IR version**
![image](https://user-images.githubusercontent.com/62356085/209466721-10d181f5-a393-4b1f-ba0e-72ffc1267a3f.png)
This bug happens also on windows not only linux
![image](https://user-images.githubusercontent.com/62356085/209466585-784cdd63-d2a9-4810-b6f0-d591f0c7937a.png)

**Log**
13.912 Error ClientMultiplayerManager.cpp:1074: mod-IndustrialRevolution3 was registered for the following events when the map was saved but has not re-registered them as a result of loading: on_tick (ID 0)
  13.912 Error ClientMultiplayerManager.cpp:1088: mod-IndustrialRevolution3 was registered for the following nth_ticks when the map was saved but has not re-registered them as a result of loading: 240
  13.912 Error ClientMultiplayerManager.cpp:99: MultiplayerManager failed: "" + multiplayer.script-event-mismatch + "
" + "
mod-IndustrialRevolution3"
  13.915 Info ClientMultiplayerManager.cpp:610: UpdateTick(2478) changing state from(ConnectedLoadingMap) to(Failed)
  13.929 Info ClientSynchronizer.cpp:228: nextHeartbeatSequenceNumber(284169074) cannot process synchronizer action(MapLoadingProgressUpdate)
  13.929 Info ClientSynchronizer.cpp:228: nextHeartbeatSequenceNumber(284169074) cannot process synchronizer action(MapDownloadingProgressUpdate)
  17.480 Info ClientMultiplayerManager.cpp:211: Quitting multiplayer connection.
  17.480 Info ClientMultiplayerManager.cpp:610: UpdateTick(2478) changing state from(Failed) to(Disconnected)

**Comment by Deadlock989** [comment] 2022-12-25 13:38
This is being caused by a failure on my part to handle conditional event registrations related to the Manifesto simulations.

I know how to fix this but will not get around to it for a couple of days.

In the meantime you should be able to connect to a multiplayer game if everyone currently on the server leaves their Manifesto windows closed for 2 minutes.

**Comment by Leximo14** [comment] 2022-12-25 13:54
Thanks your fix works. Looking forward to your official fix.
Happy Christmas after all and sorry for bothering you.

**Comment by Deadlock989** [comment] 2022-12-25 23:13
This should be fixed in 3.0.2 which will be out tomorrow or the day after. I have only been able to test limited/simple multiplayer situations so if you encounter any other multiplayer issues with 3.0.2 please do report them here.

**Closed** 2022-12-26 19:18 UTC
Labels: fixed for next version
