### ISSUE TITLE
Crash joining Multiplayer Session

### ISSUE THREAD

**Issue by meigrafd** [Deadlock989/IndustrialRevolution#255] opened 2023-07-07 12:00 UTC
**Describe the bug**
When we start a new game the first player can connect as usual but when the second joines the server crashs with following message:
![grafik](https://github.com/Deadlock989/IndustrialRevolution/assets/5682038/1e47d9ed-ca40-4906-85f2-8d60c0776bd8)

**Factorio version, IR version**
Factorio Version: 1.1.80
IR3 Version: 3.0.19

**Other mods installed**
<details>
  <summary>mod-list.json</summary>

```json

{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "aai-signal-transmission",
      "enabled": true
    },
    
    {
      "name": "aai-signals",
      "enabled": true
    },
    
    {
      "name": "aai-vehicles-chaingunner",
      "enabled": true
    },
    
    {
      "name": "aai-vehicles-flame-tank",
      "enabled": true
    },
    
    {
      "name": "aai-vehicles-flame-tumbler",
      "enabled": true
    },
    
    {
      "name": "aai-vehicles-hauler",
      "enabled": true
    },
    
    {
      "name": "aai-vehicles-laser-tank",
      "enabled": true
    },
    
    {
      "name": "aai-vehicles-miner",
      "enabled": true
    },
    
    {
      "name": "aai-vehicles-warden",
      "enabled": true
    },
    
    {
      "name": "aai-zones",
      "enabled": true
    },
    
    {
      "name": "alien-biomes",
      "enabled": true
    },
    
    {
      "name": "AsphaltPaving",
      "enabled": true
    },
    
    {
      "name": "Automatic_Train_Painter",
      "enabled": true
    },
    
    {
      "name": "A_Total_Automization_Infantry_Edition",
      "enabled": true
    },
    
    {
      "name": "belt-balancer-performance",
      "enabled": true
    },
    
    {
      "name": "Better-TrainHorn",
      "enabled": true
    },
    
    {
      "name": "bobinserters",
      "enabled": true
    },
    
    {
      "name": "botReplacer",
      "enabled": true
    },
    
    {
      "name": "ch-concentrated-solar",
      "enabled": true
    },
    
    {
      "name": "chest-auto-sort",
      "enabled": true
    },
    
    {
      "name": "CleanMap",
      "enabled": true
    },
    
    {
      "name": "combat-mechanics-overhaul",
      "enabled": true
    },
    
    {
      "name": "Configurable-Armour-Suits",
      "enabled": true
    },
    
    {
      "name": "crafting_combinator_xeraph",
      "enabled": true
    },
    
    {
      "name": "DisplayPlates",
      "enabled": true
    },
    
    {
      "name": "Dustbin",
      "enabled": true
    },
    
    {
      "name": "earlier-teleporters",
      "enabled": true
    },
    
    {
      "name": "equipment-gantry",
      "enabled": true
    },
    
    {
      "name": "factorio-reach",
      "enabled": true
    },
    
    {
      "name": "factorissimo-2-notnotmelon",
      "enabled": true
    },
    
    {
      "name": "factoryplanner",
      "enabled": true
    },
    
    {
      "name": "FactorySearch",
      "enabled": true
    },
    
    {
      "name": "flib",
      "enabled": true
    },
    
    {
      "name": "FluidMustFlow",
      "enabled": true
    },
    
    {
      "name": "FNEI",
      "enabled": true
    },
    
    {
      "name": "FuelTrainStop",
      "enabled": true
    },
    
    {
      "name": "glutenfree-aai-signal-transmission-preview",
      "enabled": true
    },
    
    {
      "name": "GUI_Unifyer",
      "enabled": true
    },
    
    {
      "name": "IndustrialRevolution3",
      "enabled": true
    },
    
    {
      "name": "IndustrialRevolution3Assets1",
      "enabled": true
    },
    
    {
      "name": "IndustrialRevolution3Assets2",
      "enabled": true
    },
    
    {
      "name": "IndustrialRevolution3Assets3",
      "enabled": true
    },
    
    {
      "name": "IndustrialRevolution3Assets4",
      "enabled": true
    },
    
    {
      "name": "IndustrialRevolution_Language_Pack",
      "enabled": true
    },
    
    {
      "name": "informatron",
      "enabled": true
    },
    
    {
      "name": "Inventory Sensor",
      "enabled": true
    },
    
    {
      "name": "ir3-early-logistics",
      "enabled": true
    },
    
    {
      "name": "IR3_Squeak_Through",
      "enabled": true
    },
    
    {
      "name": "jetpack",
      "enabled": true
    },
    
    {
      "name": "Juicy_mods",
      "enabled": true
    },
    
    {
      "name": "K1_Advanced_fluid",
      "enabled": true
    },
    
    {
      "name": "Milestones",
      "enabled": true
    },
    
    {
      "name": "miniloader",
      "enabled": true
    },
    
    {
      "name": "mining-patch-planner",
      "enabled": true
    },
    
    {
      "name": "PipeVisualizer",
      "enabled": true
    },
    
    {
      "name": "PlannerCore1-1",
      "enabled": true
    },
    
    {
      "name": "railloader",
      "enabled": true
    },
    
    {
      "name": "rec-blue-plus",
      "enabled": true
    },
    
    {
      "name": "RemoteConfiguration",
      "enabled": true
    },
    
    {
      "name": "RPGsystem",
      "enabled": true
    },
    
    {
      "name": "rusty-locale-xeraph",
      "enabled": true
    },
    
    {
      "name": "safefill",
      "enabled": true
    },
    
    {
      "name": "Shortcuts-ick",
      "enabled": true
    },
    
    {
      "name": "show-max-underground-distance",
      "enabled": true
    },
    
    {
      "name": "simhelper",
      "enabled": true
    },
    
    {
      "name": "some-zoom",
      "enabled": true
    },
    
    {
      "name": "SpidertronEnhancements",
      "enabled": true
    },
    
    {
      "name": "SpidertronPatrols",
      "enabled": true
    },
    
    {
      "name": "stdlib",
      "enabled": true
    },
    
    {
      "name": "TanksSchallGroupsfixes",
      "enabled": true
    },
    
    {
      "name": "Teleporters",
      "enabled": true
    },
    
    {
      "name": "textplates",
      "enabled": true
    },
    
    {
      "name": "Todo-List",
      "enabled": true
    },
    
    {
      "name": "train-log",
      "enabled": true
    },
    
    {
      "name": "train-pubsub",
      "enabled": true
    },
    
    {
      "name": "train-upgrader",
      "enabled": true
    },
    
    {
      "name": "Transport-Drones-On-Asphalt",
      "enabled": true
    },
    
    {
      "name": "Transport_Drones",
      "enabled": true
    },
    
    {
      "name": "Transport_Drones_Addon_PPD_1_1",
      "enabled": true
    },
    
    {
      "name": "Truce-Mod",
      "enabled": true
    },
    
    {
      "name": "underground-pipe-pack",
      "enabled": true
    },
    
    {
      "name": "Unit_Control",
      "enabled": true
    },
    
    {
      "name": "Warehousing",
      "enabled": true
    }
  ]
}
```
  
</details>

**Comment by Deadlock989** [comment] 2023-07-07 12:38
I can't reproduce this with IR 3.0.19 or 3.1.0 without any of that huge list of other mods installed - for me when player 2 joins, everything is normal.

I will need a copy of your saved game (after player 1 joins but before player 2 attempts to join) to investigate this any further.

**Comment by meigrafd** [comment] 2023-07-07 13:33
Savegame: [Hyperion - IR3.zip](https://github.com/Deadlock989/IndustrialRevolution/files/11982484/Hyperion.-.IR3.zip)

**Comment by Deadlock989** [comment] 2023-07-07 13:48
Thanks.

I'm still not able to reproduce this. Player 2 can join just fine:

![image](https://github.com/Deadlock989/IndustrialRevolution/assets/3128845/c1f175b9-a14f-4cb2-a98d-3bd115dab97b)

Looking at the error report you give above, I'm not even sure how player 2 could ever reach that code.

I will need precise, repeatable reproduction steps that lead to the same error, if you want me to investigate this further. Otherwise I can add a bit more validation around the existence of the intro cutscene furniture but that's all.

**Comment by meigrafd** [comment] 2023-07-07 14:18
Can you try to leave the Plattform befor player2 joines? 
=> Your plattform explodes and after that another player joines. Thats what we did and where it crashed

**Comment by Deadlock989** [comment] 2023-07-07 14:18
Edited to add: I did manage to find some issues when I tried loading your save in single player. The game appears to have gotten into a highly unusual state which I can't explain. It's especially unusual given that it's barely a minute old.

There should be a game surface called "IR-limbo". If this is deleted midway through the intro cutscene, it would explain the error above and others like it - but it has nothing to do with player 2 or multiplayer at all.

- Are you using a mod which can delete entire surfaces? 
- Did you start this game with an older version of the mod, save it during the initial cutscene before it finished, and then re-load it in a later version?

Otherwise I have added a bit more validation around things that can be interfered with by other mods during the progress of the cutscene, but your saved game is not really in a state I can rescue.

**Comment by Deadlock989** [comment] 2023-07-07 14:21
> Can you try to leave the Plattform befor player2 joines? => Your plattform explodes and after that another player joines. Thats what we did and where it crashed

This works fine for me, if I start a new game, but not in your Hyperion save, which is somehow mangled.

**Comment by meigrafd** [comment] 2023-07-07 15:42
Ok i've created a new game and this time i saved at a state where player1 was really spawnd - last time i saved in a state where the spawn-process was ongoing or so. Now it works 👍 problem solved.
Thanks for your time and support!

**Comment by Deadlock989** [comment] 2023-07-07 16:23
It has helped me pin down a general issue that affects single player as well: if the game is saved before the initial "first player" transmat cutscene finishes, and then the mod version changes and the saved game is reloaded, the game will most likely be put into a broken state by the mod's own configuration refresh script.

**Comment by Deadlock989** [comment] 2023-07-07 16:28
Fixed by no longer deleting the "limbo" surface used by transmats and a couple of other mechanics on mod configuration change; intro cutscene waypoints also check more thoroughly for entity validity.

**Closed** 2023-07-14 13:40 UTC
Labels: fixed for next version
