### ISSUE TITLE
Steam inserter graphics backwards?

### ISSUE THREAD

**Issue by mspielberg** [Deadlock989/IndustrialRevolution#10] opened 2021-02-10 01:28 UTC
Electric inserters "point" in the direction of flow, where the side with 2 legs is towards the source and the side with 1 leg is towards the destination. Steam inserters reverse this. If this is intentional, feel free to close this issue. If unintentional, it might have to do with the oddity that Factorio's inserters have their directions reversed: an inserter moving items from north-to-south has direction `north`, for example. Enjoying the mod, especially the steam inserters!

**Comment by Deadlock989** [comment] 2021-02-10 02:15
You're right, I hadn't noticed. What's odd is that the sprite sheet is the same as every other inserter. It is probably caused by me abusing the integration_patch property - because the bulk of the inserter platform is piping, it can't be on the below-object-above-ground render layer that inserter platforms are hardcoded, or shadows from neighbouring pipes get drawn over it - so I used the integration_patch sprite instead, which has a specifiable render layer. For whatever reason, the directions on the integration_patch sprite seem to be 180 degrees from the platform picture.

I can think of a couple of ways of fiddling with it, worst case is just changing the sprite sheet around.

**Comment by Deadlock989** [comment] 2021-02-10 14:01
Fixed by manually specifying sprite per direction with an x offset

**Closed** 2021-02-10 14:02 UTC
Labels: fixed for next version
