### ISSUE TITLE
Flip blueprint doesn't work for steam items

### ISSUE THREAD

**Issue by husnikadam** [Deadlock989/IndustrialRevolution#89] opened 2021-12-21 14:14 UTC
**Describe the bug**
The following steam items can't be flipped (neither by F or G default keybind) in place blueprint regime:
steam inserter
long handed steam inserter
aetheric lamp
steam mining drill
steam crusher
steam mixer
steam assembler
steam laboratory

Other steam items seem to be able to be flipped. Other, electric machine variants of the machines above seem to be flippable also.

![Screenshot 2021-12-21 151419](https://user-images.githubusercontent.com/25010777/146944244-804ed1c4-ca58-4f23-a0f8-acc2fd3b16e1.png)

**Factorio version and OS/platform**
1.1.49, Windows 11 home, version 21H2, build 10.0.22000.376

**List other mods installed**
Allien Biomes 0.6.5
Allien Biomes High-Res Terain 0.6.1
Base Mod 1.1.49
Black Rubber Belts 1.0.0
Cold Biters 1.1.1
Explosive Biters 1.1.35
Factorio Library 0.9.2
FNEI 0.4.1
Industrial Revolution 2 2.3.2
Larger Lamps 1.5.0
Rate Calculator 2.4.2

P.S. originally tested on Industrial Revolution 2 v 2.3.1, Rate Calculator 2.2.2 and Factorio Library 0.8.3, but the bug is still present in the versions mentioned above.

**Comment by Deadlock989** [comment] 2021-12-21 14:59
Duplicate of #35 - this is an omission in the base game's logic for blueprint flipping, where fluid power inputs are not accounted for in the same way that fluid ingredient inputs are. As far as I know there's nothing that can be done about it without changes to the base game.

**Closed by Deadlock989** 2021-12-21 14:59 UTC

**Comment by husnikadam** [comment] 2021-12-21 15:11
I'll report to Factorio developers then. Thank you and sorry for duplicating the ticket,
