### ISSUE TITLE
Upgrade steam inserters with upgrade tool

### ISSUE THREAD

**Issue by DurinMusicspear** [Deadlock989/IndustrialRevolution#62] opened 2021-06-13 20:26 UTC
The upgrade tool only allows upgrade from steam inserter to long hand steam inserter and no other inserters. I would like to have an option to upgrade them to electric steam inserter. Is there a reason that is not possible/implemented?

**Comment by Deadlock989** [comment] 2021-06-13 20:41
Duplicate of #13

**Closed by Deadlock989** 2021-06-13 20:41 UTC

**Comment by DurinMusicspear** [comment] 2021-06-14 07:48
Right, did not see that one, thanks!
