### ISSUE TITLE
Polluted water does not appear in fluids production screen anymore

### ISSUE THREAD

**Issue by FrancoisDevemy5** [Deadlock989/IndustrialRevolution#400] opened 2024-03-04 02:31 UTC
Hello,

Polluted water (and also steam) does not appear anymore in the fluid production box.
It did appear at some point, but not anymore.
I can't say for sure if it is due to an update of factory or IR or some other issue.
I have started the game using IR 3.1, but don't remember which specific version it was.
<img width="1792" alt="Capture d’écran 2024-03-04 à 03 24 55" src="https://github.com/Deadlock989/IndustrialRevolution/assets/61689139/ad3fcf13-3e5f-448b-8bb4-814c9104b2a3">

**Factorio version, IR version**
Factorio 1.1.104
IR 3.1.20

**Comment by Deadlock989** [comment] 2024-03-04 07:21
Duplicate of #206

**Closed by Deadlock989** 2024-03-04 07:21 UTC
